"""create complaints table

Revision ID: 737bb0768bfd
Revises: d1ddc0e368a0
Create Date: 2026-07-28 17:54:46.196038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '737bb0768bfd'
down_revision: Union[str, Sequence[str], None] = 'd1ddc0e368a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('comments')
    op.drop_table('activities')
    op.drop_table('capa')
    op.drop_table('ai_analysis')
    op.add_column('complaints', sa.Column('title', sa.String(length=255), nullable=False))
    op.alter_column('complaints', 'complaint_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('complaints', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('PRODUCT', 'SERVICE', 'BILLING', 'DELIVERY', 'OTHER', name='complaintcategory'),
               postgresql_using='category::text::complaintcategory',
               existing_nullable=False)
    op.alter_column('complaints', 'priority',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='complaintpriority'),
               postgresql_using='priority::text::complaintpriority',
               existing_nullable=False)
    op.alter_column('complaints', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='complaintstatus'),
               postgresql_using='status::text::complaintstatus',
               existing_nullable=False)
    op.alter_column('complaints', 'customer_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('complaints', 'customer_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('complaints', 'customer_phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('complaints', 'assigned_to',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               postgresql_using='assigned_to::uuid',
               existing_nullable=True)
    op.alter_column('complaints', 'created_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               postgresql_using='created_by::uuid',
               nullable=False)
    op.alter_column('complaints', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('complaints', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_complaints_category'), 'complaints', ['category'], unique=False)
    op.create_index(op.f('ix_complaints_priority'), 'complaints', ['priority'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_foreign_key(None, 'complaints', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'complaints', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.drop_column('complaints', 'company')
    op.drop_column('complaints', 'batch_number')
    op.drop_column('complaints', 'product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('product', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('complaints', sa.Column('batch_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('complaints', sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_priority'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category'), table_name='complaints')
    op.alter_column('complaints', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('complaints', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('complaints', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('complaints', 'assigned_to',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('complaints', 'customer_phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('complaints', 'customer_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('complaints', 'customer_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('complaints', 'status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='complaintstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('complaints', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='complaintpriority'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('complaints', 'category',
               existing_type=sa.Enum('PRODUCT', 'SERVICE', 'BILLING', 'DELIVERY', 'OTHER', name='complaintcategory'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('complaints', 'complaint_number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('complaints', 'title')
    op.create_table('ai_analysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('root_cause', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('ai_analysis_complaint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_analysis_pkey'))
    )
    op.create_table('capa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('capa_complaint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('capa_pkey'))
    )
    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('activities_complaint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('activities_pkey'))
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('comments_complaint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_table('attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('filepath', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('attachments_complaint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attachments_pkey'))
    )
    # ### end Alembic commands ###
