"""add under_review status

Revision ID: d791196280a6
Revises: 737bb0768bfd
Create Date: 2026-07-28 19:57:23.409608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd791196280a6'
down_revision: Union[str, Sequence[str], None] = '737bb0768bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE complaintstatus ADD VALUE 'UNDER_REVIEW'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
