import Card from "@/components/ui/Card/Card";
import Button from "@/components/ui/Button/Button";
import { Lightbulb, Sparkles } from "lucide-react";

export default function InsightCard() {
  return (
    <Card className="h-full">
      <div className="flex items-center gap-3 mb-6">
        <div className="rounded-lg bg-yellow-100 p-3">
          <Lightbulb className="text-yellow-600" size={22} />
        </div>

        <div>
          <h2 className="text-xl font-semibold">AI Insights</h2>
          <p className="text-sm text-gray-500">
            Generated by Groq + LangGraph
          </p>
        </div>
      </div>

      <div className="space-y-5">
        <div className="rounded-lg bg-blue-50 p-4">
          <p className="font-medium">
            Quality complaints increased by{" "}
            <span className="font-bold text-red-600">18%</span>{" "}
            this week.
          </p>
        </div>

        <div className="rounded-lg bg-green-50 p-4">
          <p>
            Most complaints are related to{" "}
            <strong>Packaging Damage.</strong>
          </p>
        </div>

        <div className="rounded-lg bg-yellow-50 p-4">
          <p>
            Suggested Action:{" "}
            <strong>Inspect Batch #B-128.</strong>
          </p>
        </div>
      </div>

      <Button className="mt-6 w-full flex items-center justify-center gap-2">
        <Sparkles size={18} />
        Generate New Insight
      </Button>
    </Card>
  );
}
